# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2022-present Fewtarius

name: repo-clean
on:
  workflow_dispatch:

jobs:
  clean-dev-releases:
    runs-on: ubuntu-22.04
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          repo: JustEnoughLinuxOS/distribution
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
